const genAI = require("../config/gemini");

/**
 * Generates questions from the provided text using Gemini API.
 * @param {string} text - The text to generate questions from.
 * @returns {Promise<Object[]>} - A list of generated questions.
 */
const generateQuestions = async (text) => {
  try {
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    // Flash has a huge context window, but we still cap it to a reasonable size 
    const maxChars = 100000; 
    const truncatedText = text.substring(0, maxChars);

    const prompt = `
      You are an expert educator. Based on the following text, generate 5 to 10 high-quality Multiple Choice Questions (MCQs/QCM) to test understanding.
      Provide the output strictly in JSON format as an array of objects.
      Each object must have:
      - "question": The question text
      - "options": An array of 4 possible answers
      - "answer": The correct answer from the options array
      
      Text:
      ${truncatedText}
      
      Output format:
      [
        { 
          "question": "...", 
          "options": ["Option A", "Option B", "Option C", "Option D"], 
          "answer": "Option A" 
        },
        ...
      ]
    `;

    console.log("Calling Gemini AI with model: gemini-2.5-flash...");
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const responseText = response.text();
    
    console.log("Raw AI Response received, length:", responseText.length);

    // Find the JSON part in case Gemini adds markdown backticks
    const jsonMatch = responseText.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      console.error("DEBUG: Model returned text that doesn't contain a JSON array:", responseText);
      throw new Error("Gemini returned invalid format (no JSON array found)");
    }

    try {
      const questions = JSON.parse(jsonMatch[0]);
      return questions;
    } catch (parseError) {
      console.error("DEBUG: JSON Parse Error on text:", jsonMatch[0]);
      throw new Error("Failed to parse the JSON generated by AI");
    }
  } catch (error) {
    console.error("Detailed Gemini Error:", error);
    
    // Check if it's an API Key issue
    if (error.message.includes("API_KEY_INVALID")) {
      throw new Error("Your Gemini API Key is invalid. Please check your .env file.");
    }
    
    // Check if it's a Model issue
    if (error.message.includes("model not found") || error.message.includes("404")) {
      throw new Error(`The model 'gemini-2.5-flash' was not found. Try 'gemini-1.5-flash' instead.`);
    }

    throw new Error(`AI Generation failed: ${error.message}`);
  }
};

module.exports = {
  generateQuestions,
};
