const genAI = require("../config/gemini");

/**
 * Generates questions from the provided text using Gemini API.
 * @param {string} text - The text to generate questions from.
 * @returns {Promise<Object[]>} - A list of generated questions.
 */
const generateQuestions = async (text) => {
  try {
    // Using gemini-1.5-flash for stability as recommended for UPF course processing.
    const modelId = "gemini-2.5-flash";

    // Trimming text to a reasonable size (approx 10-15 pages) to ensure fast processing.
    const maxChars = 30000; 
    const truncatedText = text.substring(0, maxChars);

    const prompt = `
        You are a Professor at UPF (Université Privée de Fès). Based on the following extracted text from a course material, generate a 5-question multiple choice quiz to help students study.
        
        Return the result as a raw JSON object with this exact structure:
        {
          "quiz_title": "string",
          "questions": [
            {
              "question": "string",
              "options": ["Option A", "Option B", "Option C", "Option D"],
              "correct_answer_index": 0,
              "explanation": "Brief explanation why this is the correct answer"
            }
          ]
        }

        IMPORTANT: Return ONLY the JSON object. Do not enclose it in markdown code blocks.

        Extracted Course Text:
        ---
        ${truncatedText}
    `;

    console.log(`Calling Gemini AI (${modelId}) with UPF Professor persona...`);
    
    // Using the new @google/genai SDK syntax
    const result = await genAI.models.generateContent({
      model: modelId,
      contents: prompt,
    });
    
    // In @google/genai, result.text is a property, not a method
    const responseText = result.text;
    
    console.log("Raw AI Response received, length:", responseText.length);

    // Find the JSON part
    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.error("DEBUG: Model returned text that doesn't contain a JSON object:", responseText);
      throw new Error("Gemini returned invalid format (no JSON object found)");
    }

    try {
      const quizData = JSON.parse(jsonMatch[0]);
      return quizData;
    } catch (parseError) {
      console.error("DEBUG: JSON Parse Error on text:", jsonMatch[0]);
      throw new Error("Failed to parse the JSON generated by AI");
    }
  } catch (error) {
    console.error("Detailed Gemini Error:", error);
    
    // Check if it's an API Key issue
    if (error.message.includes("API_KEY_INVALID")) {
      throw new Error("Your Gemini API Key is invalid. Please check your .env file.");
    }
    
    // Check if it's a Model issue
    if (error.message.includes("model not found") || error.message.includes("404")) {
      throw new Error(`The model 'gemini-1.5-flash' was not found. Please verify your API permissions.`);
    }

    throw new Error(`AI Generation failed: ${error.message}`);
  }
};

module.exports = {
  generateQuestions,
};
